linters:
  presets:
    - bugs
    - error
    - import
    - metalinter
    - module
    - unused

  enable:
    - testifylint

  disable:
    # preset error
    - err113 # Very annoying to define static errors everywhere
    - wrapcheck # Very annoying to wrap errors everywhere
    # preset import
    - depguard

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hetznercloud)

  gosec:
    excludes:
      # As of golangci-lint v1.60.3, this rule is still enabled by default, which causes problems.
      # We disable it manually for now until a new golangci-lint version is released which fixes this.
      # See https://github.com/securego/gosec/issues/1185
      - G115

  exhaustive:
    # Switch cases with a default case should be exhaustive.
    default-signifies-exhaustive: true

  gosmopolitan:
    # We want to allow the use of time.Local()
    allow-time-local: true

  # TODO: This is required for the storage-boxes branch, remove before merging to main!
  gomoddirectives:
    replace-allow-list:
      - github.com/hetznercloud/hcloud-go/v2
