version: 2
before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      main: ./cmd/hcloud/main.go
      binary: hcloud
      flags:
        - -trimpath
      ldflags:
        - -s
        - -w
        - -X {{ .ModulePath }}/internal/version.version={{ .Version }}
        - -X {{ .ModulePath }}/internal/version.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
      env:
        - CGO_ENABLED=0

    id: hcloud-build
    goos: [freebsd, windows, linux]
    goarch: [amd64, arm, arm64, "386"]
    goarm: ["6", "7"]

  - <<: *build_defaults
    id: hcloud-build-darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        - cmd: >
            {{- if index .Env "APPLE_CERTIFICATE_P12_PASSWORD" -}}
            rcodesign sign
              --p12-file certificate.p12
              --p12-password "{{ .Env.APPLE_CERTIFICATE_P12_PASSWORD }}"
              --code-signature-flags runtime
              "{{ .Path }}"
            {{- else -}}
            echo "skipping rcodesign sign hook!"
            {{- end -}}
          output: true

snapshot:
  name_template: "{{ .Version }}-dev+{{ .ShortCommit }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: all
    signature: ${artifact}.sig
    id: hcloud-sign
    ids:
      - hcloud-build
      - hcloud-build-darwin
    args:
      - --batch
      - --local-user=github-bot@hetzner-cloud.de
      - --pinentry-mode=loopback
      - --output=${signature}
      - --detach-sign
      - ${artifact}

archives:
  - id: hcloud-archive
    builds:
      - hcloud-build
      - hcloud-build-darwin
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md

release:
  draft: false
