builds:
  - id: "hcloud-macos-build"
    main: ./cmd/hcloud/main.go
    binary: hcloud
    ldflags:
      - -w -X github.com/hetznercloud/cli/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - cmd: sudo gon -log-level TRACE gon.hcl
          output: true
  - id: "hcloud-macos-arm-build"
    main: ./cmd/hcloud/main.go
    binary: hcloud
    ldflags:
      - -w -X github.com/hetznercloud/cli/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - cmd: sudo gon -log-level TRACE gon_arm64.hcl
          output: true
before:
  hooks:
    - go mod tidy

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  draft: true
  name_template: "hcloud v{{.Version}}"

signs:
  - artifacts: all
    signature: "${artifact}.sig"
    id: hcloud-sign
    ids:
      - hcloud-macos-build
      - hcloud-macos-arm-build
    args: ["--batch", "-u", "github-bot@hetzner-cloud.de", "--pinentry-mode", "loopback", "--output", "${signature}", "--detach-sign", "${artifact}"]

archives:
  - id: hcloud-archive
    builds:
      - hcloud-macos-build
      - hcloud-macos-arm-build
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md
