builds:
  - id: "hcloud"
    main: ./cmd/hcloud/main.go
    binary: hcloud
    ldflags:
      - -w -X github.com/hetznercloud/cli/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7

  - id: "hcloud-macos"
    main: ./cmd/hcloud/main.go
    binary: hcloud
    ldflags:
      - -w -X github.com/hetznercloud/cli/cli.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64

before:
  hooks:
    - go mod tidy

release:
  draft: true
  name_template: "hcloud v{{.Version}}"
  disable: true

signs:
  - artifacts: all
    ids:
      - hcloud
    args: ["--batch", "-u", "github-bot@hetzner-cloud.de", "--pinentry-mode", "loopback", "--output", "${signature}", "--detach-sign", "${artifact}"]
  - signature: "./dist/${artifact}.dmg"
    ids:
      - hcloud-macos
    cmd: gon
    args:
      - gon.hcl
      - -log-level=info
      - -log-json
    artifacts: all

archives:
  - id: hcloud
    builds:
      - hcloud
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip

    files:
      - LICENSE
      - CHANGES.md
      - README.md
