before:
  hooks:
    - go mod tidy

builds:
  - id: hcloud-build
    main: ./cmd/hcloud/main.go
    binary: hcloud
    ldflags:
      - -w
      - -X {{ .ModulePath }}/internal/version.version={{ .Version }}
      - -X {{ .ModulePath }}/internal/version.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - "386"
    goarm:
      - "6"
      - "7"

  - id: hcloud-build-darwin
    main: ./cmd/hcloud/main.go
    binary: hcloud
    ldflags:
      - -w
      - -X {{ .ModulePath }}/internal/version.version={{ .Version }}
      - -X {{ .ModulePath }}/internal/version.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: bash script/gon.sh "{{ .Path }}"
          output: true

snapshot:
  name_template: "{{ .Version }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: all
    signature: ${artifact}.sig
    id: hcloud-sign
    ids:
      - hcloud-build
      - hcloud-build-darwin
    args:
      - --batch
      - --local-user=github-bot@hetzner-cloud.de
      - --pinentry-mode=loopback
      - --output=${signature}
      - --detach-sign
      - ${artifact}

archives:
  - id: hcloud-archive
    builds:
      - hcloud-build
      - hcloud-build-darwin
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md

release:
  draft: false
