version: 2
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - go run ./scripts manpages

builds:
  - <<: &build_defaults
      main: ./cmd/hcloud/main.go
      binary: hcloud
      flags:
        - -trimpath
      ldflags:
        - -s
        - -w
        - -X {{ .ModulePath }}/internal/version.version={{ .Version }}
        - -X {{ .ModulePath }}/internal/version.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
      env:
        - CGO_ENABLED=0

    id: hcloud-build-linux-main
    goos: [linux]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: hcloud-build-linux-other
    goos: [ linux ]
    goarch: [ arm, "386" ]
    goarm: [ "6", "7" ]

  - <<: *build_defaults
    id: hcloud-build-freebsd
    goos: [ freebsd ]
    goarch: [amd64, arm, arm64, "386"]
    goarm: ["6", "7"]

  - <<: *build_defaults
    id: hcloud-build-windows
    goos: [ windows ]
    goarch: [ amd64, arm64, "386" ]

  - <<: *build_defaults
    id: hcloud-build-darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    hooks:
      post:
        # sign-and-notarize might fails if the Apple license agreement is not signed.
        # This ensures that the release process continues instead of stopping and having
        # a release without assets. The error is reported at the end of the CI job.
        - cmd: bash -c 'quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} || touch sign-and-notarize.error'
          output: true

nfpms:
  - id: default
    file_name_template: "{{ .ConventionalFileName }}"
    package_name: hcloud-cli
    ids: [hcloud-build-linux-main]
    provides: [hcloud]
    vendor: Hetzner Cloud GmbH
    homepage: https://github.com/hetznercloud/cli
    maintainer: Hetzner Cloud GmbH <support-cloud@hetzner.com>
    formats:
      - deb
      - rpm
    description: A command-line interface for Hetzner Cloud
    license: MIT

    contents:
      - src: ./completions/hcloud.bash
        dst: /usr/share/bash-completion/completions/hcloud
        file_info:
          mode: 0644
      - src: ./completions/hcloud.fish
        dst: /usr/share/fish/vendor_completions.d/hcloud.fish
        file_info:
          mode: 0644
      - src: ./completions/hcloud.zsh
        dst: /usr/share/zsh/vendor-completions/_hcloud
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/hcloud/license
        file_info:
          mode: 0644
      - src: ./manpages/*
        dst: /usr/share/man/man1/
        file_info:
          mode: 0644

kos:
  - id: container-images
    build: hcloud-build-linux-main
    main: ./cmd/hcloud/
    repositories:
      - hetznercloud/cli
    platforms:
      - linux/amd64
      - linux/arm64
    base_image: alpine
    bare: true
    labels:
      org.opencontainers.image.source: https://github.com/hetznercloud/cli
    tags:
      - latest
      - "{{.Tag}}"
    ldflags:
      - -s
      - -w
      - -X {{ .ModulePath }}/internal/version.version={{ .Version }}
      - -X {{ .ModulePath }}/internal/version.versionPrerelease={{- if .IsSnapshot -}}dev+{{ .ShortCommit }}{{- end -}}
      - -X {{ .ModulePath }}/internal/state/config.defaultConfigPathOverride=/config.toml

snapshot:
  version_template: "{{ .Version }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: all
    signature: ${artifact}.sig
    id: hcloud-sign
    args:
      - --batch
      - --local-user=github-bot@hetzner-cloud.de
      - --pinentry-mode=loopback
      - --output=${signature}
      - --detach-sign
      - ${artifact}

archives:
  - id: hcloud-archive
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format_overrides:
      - goos: windows
        formats: [zip]

    files:
      - LICENSE
      - README.md
      - docs/**/*

release:
  draft: false
  prerelease: auto
