[tools]
go = "1.25.8"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"github:golangci/golangci-lint" = "2.11.4"
"github:goreleaser/goreleaser" = "v2.14.3"
"github:anchore/quill" = "v0.7.1"
"github:jstemmer/go-junit-report" = "v2.1.0"
