[tools]
go = "1.26.5"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"github:golangci/golangci-lint" = "2.12.2"
"github:goreleaser/goreleaser" = "v2.17.0"
"github:anchore/quill" = "v0.7.1"
"github:anchore/syft" = "v1.50.0"
"github:jstemmer/go-junit-report" = "v2.1.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.6.0"
