// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hetznercloud/cli/internal/hcapi2 (interfaces: RDNSClient)
//
// Generated by this command:
//
//	mockgen -package mock -destination zz_rdns_client_mock.go github.com/hetznercloud/cli/internal/hcapi2 RDNSClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	net "net"
	reflect "reflect"

	hcloud "github.com/hetznercloud/hcloud-go/v2/hcloud"
	gomock "go.uber.org/mock/gomock"
)

// MockRDNSClient is a mock of RDNSClient interface.
type MockRDNSClient struct {
	ctrl     *gomock.Controller
	recorder *MockRDNSClientMockRecorder
	isgomock struct{}
}

// MockRDNSClientMockRecorder is the mock recorder for MockRDNSClient.
type MockRDNSClientMockRecorder struct {
	mock *MockRDNSClient
}

// NewMockRDNSClient creates a new mock instance.
func NewMockRDNSClient(ctrl *gomock.Controller) *MockRDNSClient {
	mock := &MockRDNSClient{ctrl: ctrl}
	mock.recorder = &MockRDNSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRDNSClient) EXPECT() *MockRDNSClientMockRecorder {
	return m.recorder
}

// ChangeDNSPtr mocks base method.
func (m *MockRDNSClient) ChangeDNSPtr(ctx context.Context, rdns hcloud.RDNSSupporter, ip net.IP, ptr *string) (*hcloud.Action, *hcloud.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeDNSPtr", ctx, rdns, ip, ptr)
	ret0, _ := ret[0].(*hcloud.Action)
	ret1, _ := ret[1].(*hcloud.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ChangeDNSPtr indicates an expected call of ChangeDNSPtr.
func (mr *MockRDNSClientMockRecorder) ChangeDNSPtr(ctx, rdns, ip, ptr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeDNSPtr", reflect.TypeOf((*MockRDNSClient)(nil).ChangeDNSPtr), ctx, rdns, ip, ptr)
}
