// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hetznercloud/cli/internal/state/config (interfaces: Config)

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// ActiveContext mocks base method.
func (m *MockConfig) ActiveContext() *Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveContext")
	ret0, _ := ret[0].(*Context)
	return ret0
}

// ActiveContext indicates an expected call of ActiveContext.
func (mr *MockConfigMockRecorder) ActiveContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveContext", reflect.TypeOf((*MockConfig)(nil).ActiveContext))
}

// ContextByName mocks base method.
func (m *MockConfig) ContextByName(arg0 string) *Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextByName", arg0)
	ret0, _ := ret[0].(*Context)
	return ret0
}

// ContextByName indicates an expected call of ContextByName.
func (mr *MockConfigMockRecorder) ContextByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextByName", reflect.TypeOf((*MockConfig)(nil).ContextByName), arg0)
}

// ContextNames mocks base method.
func (m *MockConfig) ContextNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ContextNames indicates an expected call of ContextNames.
func (mr *MockConfigMockRecorder) ContextNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextNames", reflect.TypeOf((*MockConfig)(nil).ContextNames))
}

// Contexts mocks base method.
func (m *MockConfig) Contexts() []*Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Contexts")
	ret0, _ := ret[0].([]*Context)
	return ret0
}

// Contexts indicates an expected call of Contexts.
func (mr *MockConfigMockRecorder) Contexts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contexts", reflect.TypeOf((*MockConfig)(nil).Contexts))
}

// Endpoint mocks base method.
func (m *MockConfig) Endpoint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// Endpoint indicates an expected call of Endpoint.
func (mr *MockConfigMockRecorder) Endpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoint", reflect.TypeOf((*MockConfig)(nil).Endpoint))
}

// Marshal mocks base method.
func (m *MockConfig) Marshal() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockConfigMockRecorder) Marshal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockConfig)(nil).Marshal))
}

// RemoveContext mocks base method.
func (m *MockConfig) RemoveContext(arg0 *Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveContext", arg0)
}

// RemoveContext indicates an expected call of RemoveContext.
func (mr *MockConfigMockRecorder) RemoveContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContext", reflect.TypeOf((*MockConfig)(nil).RemoveContext), arg0)
}

// SetActiveContext mocks base method.
func (m *MockConfig) SetActiveContext(arg0 *Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetActiveContext", arg0)
}

// SetActiveContext indicates an expected call of SetActiveContext.
func (mr *MockConfigMockRecorder) SetActiveContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActiveContext", reflect.TypeOf((*MockConfig)(nil).SetActiveContext), arg0)
}

// SetContexts mocks base method.
func (m *MockConfig) SetContexts(arg0 []*Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContexts", arg0)
}

// SetContexts indicates an expected call of SetContexts.
func (mr *MockConfigMockRecorder) SetContexts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContexts", reflect.TypeOf((*MockConfig)(nil).SetContexts), arg0)
}

// SetEndpoint mocks base method.
func (m *MockConfig) SetEndpoint(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEndpoint", arg0)
}

// SetEndpoint indicates an expected call of SetEndpoint.
func (mr *MockConfigMockRecorder) SetEndpoint(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEndpoint", reflect.TypeOf((*MockConfig)(nil).SetEndpoint), arg0)
}

// Write mocks base method.
func (m *MockConfig) Write() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write")
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockConfigMockRecorder) Write() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockConfig)(nil).Write))
}
