name: Build

on:
  push:
    branches: [main]
  pull_request:

env:
  GOTOOLCHAIN: local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up tools
        uses: jdx/mise-action@9e7f7633ff6f6d6048a9418a68d48f288f50eb14 # v4
        with:
          version: 2026.8.4 # renovate: datasource=github-releases depName=jdx/mise

      - name: Run GoReleaser
        run: goreleaser release --clean --snapshot --skip=sign

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Preview Binaries
          path: dist/hcloud-*/hcloud

      - name: Check for release errors
        run: scripts/check-release-error.sh
