name: Release-please

on:
  push:
    branches: [main]

jobs:
  release-please:
    # Do not run on forks.
    if: github.repository == 'hetznercloud/cli'

    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.HCLOUD_BOT_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
