name: Releaser-pleaser

on:
  push:
    branches: [main]
  pull_request_target:
    types:
      - edited
      - labeled
      - unlabeled

concurrency:
  group: releaser-pleaser
  cancel-in-progress: true

jobs:
  releaser-pleaser:
    # Do not run on forks.
    if: github.repository == 'hetznercloud/cli'

    runs-on: ubuntu-latest
    steps:
      - name: releaser-pleaser
        uses: apricote/releaser-pleaser@93a3e2c401320206dcd9a9b7a5bbc0850072b3c6 # v0.9.0
        with:
          token: ${{ secrets.HCLOUD_BOT_TOKEN }}
          extra-files: |
            internal/version/version.go
