name: Close stale issues

on:
  schedule:
    - cron: "30 12 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write

    uses: hetznercloud/.github/.github/workflows/stale.yml@main
